default_job = "clippy-esp"

[jobs]

[jobs.test]
command = ["just", "test"]
need_stdout = false

[jobs.check-drv]
command = ["just", "check-drv"]
need_stdout = false

[jobs.check-esp]
command = ["just", "check-esp"]
need_stdout = false

[jobs.check-lib]
command = ["just", "check-lib"]
need_stdout = false

[jobs.check-back]
command = ["just", "check-back"]
need_stdout = false

[jobs.check-front]
command = ["just", "check-front"]
need_stdout = false

[jobs.check-stm]
command = ["just", "check-stm"]
need_stdout = false

[jobs.clippy-drv]
command = ["just", "clippy-drv"]
need_stdout = false

[jobs.clippy-esp]
command = ["just", "clippy-esp"]
need_stdout = false

[jobs.clippy-lib]
command = ["just", "clippy-lib"]
need_stdout = false

[jobs.clippy-back]
command = ["just", "clippy-back"]
need_stdout = false

[jobs.clippy-front]
command = ["just", "clippy-front"]
need_stdout = false

[jobs.clippy-stm]
command = ["just", "clippy-stm"]
need_stdout = false

[keybindings]
c = "job:test"
q = "job:check-esp"
g = "job:check-stm"
t = "job:check-lib"
s = "job:check-drv"
v = "job:check-back"
d = "job:check-front"
shift-q = "job:clippy-esp"
shift-g = "job:clippy-stm"
shift-t = "job:clippy-lib"
shift-s = "job:clippy-drv"
shift-v = "job:clippy-back"
shift-d = "job:clippy-front"
